### ISSUE TITLE
Remove FOSDEM references

### ISSUE THREAD

**Issue by th0br0** [abate/fosdem-companion-android#3]

**Comment by abate** [comment]
I'm not sure this is a good move. If we add something to this fork, this patch would make it a bit more tedious to contribute back upstream.

**Comment by th0br0** [comment]
Merging will be manual anyway. And if we publish to the play store next week, we should have another package name than they do.

Or are there other concerns?

**Comment by abate** [comment]
no. this is a solid reason to do it. I didn't think about the playstore.
