### ISSUE TITLE
List events by barrio per day

### ISSUE THREAD

**Issue by th0br0** [abate/fosdem-companion-android#7]
Current default is listing all by day.

**Comment by abate** [comment]
I wasn't clear. Atm we have Day -> Barrios -> Events
I would like to have something like 
- Day -> Activity (Track) -> Events
and
Day -> Barrios -> Events

I was thinking more of a way to replace the Speakers listing with the barrio listing ... 

I think this involves a bit of work on the xml file. I'll try to take care of this ...

**Comment by abate** [comment]
I fixed this. now 
Activities : Day -> Category -> Event
Host : Barrios -> Events
